### ISSUE TITLE
Cool site header seems broken on iOS safari

### ISSUE THREAD

**Issue by jeffthemaximum** [jellypbc/poster#116]
**Describe the bug**
The site header of https://jellypbc.com is blank when viewing that page on iOS safari. It does work on desktop chrome. 

**Steps To Reproduce**

Visit https://jellypbc.com on iOS safari.

**Expected behavior**
You should see the normal header, I forget what it says, but it has the green spotlight and says something about Denny and Cindy.

**Screenshots**
.See pic:

![B2084FF1-6F1C-4807-952C-B86674821EA1](https://user-images.githubusercontent.com/10401528/75736292-ce267f00-5cca-11ea-96a9-edee04191091.png)

**Additional context**
Desktop, mobile, OS, browser version, etc.

Mobile iOS safari
iOS 12.4.1 don’t judge me

**Comment by yash-dani** [comment]
It seems to be there just not visible 
![682E4941-C54F-46BD-9D21-840DB61D7151](https://user-images.githubusercontent.com/41090933/75736517-60c71e00-5ccb-11ea-8ecf-d2217b99e9b9.png)

**Comment by cindywu** [comment]
code lives over here on gitlab https://gitlab.com/jellylabs/jelly we need to consolidate

**Comment by yash-dani** [comment]
root of the issue seems to be the "mix-blend-mode" argument in the .header selector. this is due to it not being supported on all browsers 
https://caniuse.com/#feat=css-mixblendmode

**Comment by cindywu** [comment]
we plan to migrate jellypbc.com to use poster https://linear.app/issue/JEL-80/migrate-jellypbccom-blog-to-poster
