### ISSUE TITLE
Inline comment text size for Title too big

### ISSUE THREAD

**Issue by cindywu** [jellypbc/poster#161]
The text size for inline comments on Titles is too big. To resolve this bug, update CSS so inline comment text styles match inline comment text styles for body content.

![Predicting protein structures with a multiplayer online game 2020-04-27 11-35-16](https://user-images.githubusercontent.com/1177031/80423385-ab07ee00-887b-11ea-935f-8e67d5fe0a5d.png)

https://poster.jellypbc.com/@nicolegsharpe/gxookp-predicting-protein-structures-with-a-multiplayer-online-game-2

**Comment by dennyluan** [comment]
This is now fixed.
