### ISSUE TITLE
User unable to delete comment

### ISSUE THREAD

**Issue by cindywu** [jellypbc/poster#162]
![Kapture 2020-04-27 at 13 53 10](https://user-images.githubusercontent.com/1177031/80431913-781b2580-888e-11ea-9b48-421dd7ca812e.gif)

1. add inline comment 
2. delete comment (deleted comments disappears)
3. refresh the page (deleted comment reappears)

**Comment by cindywu** [comment]
I was able to reproduce with my @cindy admin account.

**Comment by dennyluan** [comment]
Closing as this is now fixed.
