### ISSUE TITLE
When User2 replies to User1 comment User2 comment fails to save

### ISSUE THREAD

**Issue by cindywu** [jellypbc/poster#163]
![Kapture 2020-04-27 at 14 06 56](https://user-images.githubusercontent.com/1177031/80432636-85391400-8890-11ea-97b3-f4dde10e9b91.gif)

1. User1 comments on a post
2. User2 replies to that comment
3. Refresh browser (User 2 comment is missing)

**Comment by dennyluan** [comment]
Seems to be solved, so will close.
