### ISSUE TITLE
User cannot view text if they access link using back button

### ISSUE THREAD

**Issue by yash-dani** [jellypbc/poster#167]
**Describe the bug**
Text on Jelly is not visible if URL is accessed by hitting back button on browser. 

**Steps To Reproduce**
1. User clicks on a link while viewing a Jelly Paper
2. hits back button on browser
3. Text on page is empty unless page is refreshed 

**Expected behavior**
Text should be visible when hitting the back button.

**Screenshots**
![jelly bug](https://user-images.githubusercontent.com/41090933/80520542-91d46f80-8957-11ea-9bf1-af710fdfd5f0.gif)

**Comment by dennyluan** [comment]
Yup, this is because of turbolinks, need to remount or maybe look into using react memoization for this.
