### ISSUE TITLE
post not autosaving

### ISSUE THREAD

**Issue by cindywu** [jellypbc/poster#169]
"failed: error during websocket handshake: Unexpected response code: 404"

![image](https://user-images.githubusercontent.com/1177031/80647443-2dbeb380-8a0a-11ea-85b8-670f8bc697e5.png)

![Kapture 2020-04-29 at 10 59 37](https://user-images.githubusercontent.com/1177031/80646690-e97ee380-8a08-11ea-927d-66c3239ed4c6.gif)

search for the post
write some text
refresh the page
the text will be missing

**Comment by cindywu** [comment]
comments save. updating text in body does not save.

**Comment by dennyluan** [comment]
This should be fixed now as well, closing.
