### ISSUE TITLE
support html in titles on homepage

### ISSUE THREAD

**Issue by cindywu** [jellypbc/poster#52]
Scientific names in paper titles use italics, so to resolve this issue... support italics in titles on homepage. 

![Jellyposter 2020-01-19 19-08-27](https://user-images.githubusercontent.com/1177031/72700198-3e988880-3aef-11ea-8aa5-580a38f2efb7.png)

**Comment by dennyluan** [comment]
Ah this is because we recently changed the parsing technique on titles. We likely want to preserve the italics right?

**Comment by cindywu** [comment]
> We likely want to preserve the italics right?

Yes, we want to preserve italics in titles. 

Our post cards no longer show html. Closing this issue because we allow user to edit the title text adding italics.
