### ISSUE TITLE
did not parse text, only parsed figures

### ISSUE THREAD

**Issue by cindywu** [jellypbc/poster#63]
when this paper was uploaded it got some figures, but no text

https://poster.jellypbc.com/posts/3d-tooth-segmentation-and-labeling-using-deep-convolutional-neural-networks

i suspect that this happens when the user refreshes the browser too quickly. will need to play with this more to try to reproduce the bug.

https://storage.googleapis.com/jellyposter-store/d73af77c62389ea015258aee15b326fe.pdf

i tried to upload the paper myself and got all the parsed text. i waited a long time before refreshing the page...

https://poster.jellypbc.com/posts/fciipxitjwcfpquipedi

**Comment by dennyluan** [comment]
will try to address this in upcoming PR

**Comment by cindywu** [comment]
tested with the same paper mentioned above and we are returning text and figures. closing.
