### ISSUE TITLE
post to login page back to post results in post with no content

### ISSUE THREAD

**Issue by cindywu** [jellypbc/poster#89]
when logged out 

1. go to a post (post has contents in title and body)
2. click log in the right corner
3. click back using browser

you will see a post with no contents 

4. refresh and the contents of the post come back

https://www.loom.com/share/5f25c6b36b1045e69da9669806fc6a06

![image](https://user-images.githubusercontent.com/1177031/73909032-98b77e80-484f-11ea-8a40-d8964ea80a2a.png)

**Comment by dennyluan** [comment]
This is likely our turbolinks set up - we need to trigger another reload.

**Comment by cindywu** [comment]
okie. gif of how to reproduce. 
![Kapture 2020-03-29 at 21 46 23](https://user-images.githubusercontent.com/1177031/77887739-cf35c800-7206-11ea-9a9b-736e033bd1bd.gif)

**Comment by cindywu** [comment]
Closing. This no longer an issue.

![Kapture 2020-05-10 at 12 20 03](https://user-images.githubusercontent.com/1177031/81511973-c41b9080-92b8-11ea-90fd-fdf95fc8efc0.gif)
